
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('profile/change-password/', views.change_password, name='change_password'),
    path('pending-payment/', views.pending_payment, name='pending_payment'),
    path('payment-instructions/', views.payment_instructions, name='payment_instructions'),
    path('submit-payment-proof/', views.submit_payment_proof, name='submit_payment_proof'),
    path('properties/', views.property_list, name='property_list'),
    path('properties/register/', views.register_property, name='register_property'),
    path('properties/<int:property_id>/edit/', views.edit_property, name='edit_property'),
    path('properties/<int:property_id>/delete/', views.delete_property, name='delete_property'),
    path('book-inspection/', views.book_inspection, name='book_inspection'),
    path('service-status/', views.service_status, name='service_status'),
    path('om/home/', views.om_home, name='om_home'),
    path('om/profile/', views.om_profile, name='om_profile'),
    path('om/profile/change-password/', views.om_change_password, name='om_change_password'),
    path('om/service-history/', views.om_service_history, name='om_service_history'),
    path('om/billing/', views.om_billing, name='om_billing'),
    path('om/billing/estimated/', views.om_estimated_bills, name='om_estimated_bills'),
    path('om/billing/estimated/create/', views.om_create_estimated_bill, name='om_create_estimated_bill'),
    path('om/billing/estimated/<int:estimated_bill_id>/', views.om_view_estimated_bill, name='om_view_estimated_bill'),
    path('om/service-status/', views.om_service_status, name='om_service_status'),
    path('om/service-status/<int:service_id>/update-status/', views.om_update_service_status, name='om_update_service_status'),
    path('om/service-status/<int:service_id>/edit-booking/', views.om_edit_booking, name='om_edit_booking'),
    path('om/service-status/<int:service_id>/delete-booking/', views.om_delete_booking, name='om_delete_booking'),
    path('om/service-status/<int:service_id>/book-treatment/', views.om_book_treatment, name='om_book_treatment'),
    path('om/service-reports/', views.om_service_reports, name='om_service_reports'),
    path('om/service-reports/<int:report_id>/', views.om_view_service_report, name='om_view_service_report'),
    path('om/remittance-records/', views.om_remittance_records, name='om_remittance_records'),
    path('om/manage-service-forms/', views.om_manage_service_forms, name='om_manage_service_forms'),
    path('om/manage-accounts/', views.om_manage_accounts, name='om_manage_accounts'),
    path('om/manage-accounts/<int:technician_pk>/edit/', views.om_edit_technician_account, name='om_edit_technician_account'),
    path('technician/home/', views.technician_home, name='technician_home'),
    path('technician/profile/', views.technician_profile, name='technician_profile'),
    path('technician/service-status/', views.technician_service_status, name='technician_service_status'),
    path('technician/service-status/<int:service_id>/update-status/', views.technician_update_service_status, name='technician_update_service_status'),
    path('technician/service-status/<int:service_id>/edit-booking/', views.technician_edit_booking, name='technician_edit_booking'),
    path('technician/service-status/<int:service_id>/delete-booking/', views.technician_delete_booking, name='technician_delete_booking'),
    path('technician/service-history/', views.technician_service_history, name='technician_service_history'),
    path('technician/service-reports/', views.technician_service_reports, name='technician_service_reports'),
    path('technician/service-reports/create/', views.technician_create_service_report, name='technician_create_service_report'),
    path('technician/service-reports/<int:report_id>/', views.technician_view_service_report, name='technician_view_service_report'),
]
