# Generated by Django 5.1.6 on 2026-02-18 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sangapp', '0002_property'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_service', models.CharField(max_length=255)),
                ('preferred_service_other', models.CharField(blank=True, max_length=255, null=True)),
                ('pest_problem', models.CharField(max_length=255)),
                ('pest_problem_other', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField()),
                ('time_slot', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('For Inspection', 'For Inspection'), ('Pending Payment', 'Pending Payment'), ('Scheduled', 'Scheduled'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='For Inspection', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='sangapp.customer')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='sangapp.property')),
            ],
            options={
                'db_table': 'services',
                'ordering': ['-created_at'],
            },
        ),
    ]
