# Generated by Django 5.1.6 on 2026-03-04 00:00

import django.db.models.deletion
from django.db import migrations, models


def create_default_operations_manager(apps, schema_editor):
    OperationsManager = apps.get_model('sangapp', 'OperationsManager')
    OperationsManager.objects.get_or_create(
        email='OM@companyemail.com',
        defaults={
            'first_name': 'Operations',
            'last_name': 'Manager',
            'password': 'operations_manager',
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('sangapp', '0004_alter_service_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationsManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Operations', max_length=100)),
                ('last_name', models.CharField(default='Manager', max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'operations_managers',
            },
        ),
        migrations.AddField(
            model_name='service',
            name='confirmed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TreatmentBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_service', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time_slot', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_bookings', to='sangapp.service')),
            ],
            options={
                'db_table': 'treatment_bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(create_default_operations_manager, migrations.RunPython.noop),
    ]
