# Generated by Django 5.1.6 on 2026-03-04 00:00

from django.db import migrations, models


def map_ongoing_to_for_inspection(apps, schema_editor):
    Service = apps.get_model('sangapp', 'Service')
    Service.objects.filter(status='Ongoing Inspection').update(status='For Inspection')


class Migration(migrations.Migration):

    dependencies = [
        ('sangapp', '0005_operationsmanager_service_confirmed_date_treatmentbooking'),
    ]

    operations = [
        migrations.RunPython(map_ongoing_to_for_inspection, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(
                choices=[
                    ('For Inspection', 'For Inspection'),
                    ('For Treatment', 'For Treatment'),
                    ('Ongoing Treatment', 'Ongoing Treatment'),
                    ('Pending Payment', 'Pending Payment'),
                    ('Payment Confirmed', 'Payment Confirmed'),
                    ('Completed', 'Completed'),
                    ('Cancelled', 'Cancelled'),
                ],
                default='For Inspection',
                max_length=50,
            ),
        ),
    ]
