# Generated by Django 5.1.6 on 2026-03-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sangapp', '0006_remove_ongoing_inspection_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(
                choices=[
                    ('For Inspection', 'For Inspection'),
                    ('Ongoing Inspection', 'Ongoing Inspection'),
                    ('For Treatment', 'For Treatment'),
                    ('Ongoing Treatment', 'Ongoing Treatment'),
                    ('Pending Payment', 'Pending Payment'),
                    ('Payment Confirmed', 'Payment Confirmed'),
                    ('Completed', 'Completed'),
                    ('Cancelled', 'Cancelled'),
                ],
                default='For Inspection',
                max_length=50,
            ),
        ),
    ]
