# Generated by Django 6.0.2 on 2026-03-04 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sangapp', '0008_technician'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_report', to='sangapp.service')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_reports', to='sangapp.technician')),
            ],
            options={
                'db_table': 'service_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceReportArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=255)),
                ('infestation_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=20)),
                ('spray', models.BooleanField(default=False)),
                ('mist', models.BooleanField(default=False)),
                ('rat_bait', models.BooleanField(default=False)),
                ('powder', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True)),
                ('recommendation', models.TextField(blank=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treated_areas', to='sangapp.servicereport')),
            ],
            options={
                'db_table': 'service_report_areas',
            },
        ),
        migrations.CreateModel(
            name='ServiceReportChemical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chemical_name', models.CharField(max_length=255)),
                ('unit_measure', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chemicals', to='sangapp.servicereport')),
            ],
            options={
                'db_table': 'service_report_chemicals',
            },
        ),
    ]
