# Generated by Django 6.0.2 on 2026-03-04 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sangapp', '0009_servicereport_servicereportarea_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimatedBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operations_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimated_bills', to='sangapp.operationsmanager')),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estimated_bill', to='sangapp.service')),
            ],
            options={
                'db_table': 'estimated_bills',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EstimatedBillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estimated_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sangapp.estimatedbill')),
            ],
            options={
                'db_table': 'estimated_bill_items',
            },
        ),
    ]
