# Generated by Django 6.0.2 on 2026-03-09 10:06

from django.db import migrations, models


def migrate_legacy_estimated_bill_status(apps, schema_editor):
    Service = apps.get_model('sangapp', 'Service')
    Service.objects.filter(status='Estimated Bill Confirmed').update(status='For Treatment')


class Migration(migrations.Migration):

    dependencies = [
        ('sangapp', '0012_alter_service_status_add_estimated_bill_states'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='om_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(migrate_legacy_estimated_bill_status, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('For Confirmation', 'For Confirmation'), ('For Inspection', 'For Inspection'), ('Ongoing Inspection', 'Ongoing Inspection'), ('Estimated Bill Created', 'Estimated Bill Created'), ('For Treatment', 'For Treatment'), ('Ongoing Treatment', 'Ongoing Treatment'), ('Pending Payment', 'Pending Payment'), ('Payment Confirmed', 'Payment Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='For Confirmation', max_length=50),
        ),
    ]
