# Generated by Django 6.0.2 on 2026-03-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sangapp', '0013_service_om_seen_at_alter_service_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='inspection_confirmed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='treatment_confirmed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
