# Generated by Django 6.0.2 on 2026-03-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sangapp', '0016_invoiceitemoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('For Confirmation', 'For Confirmation'), ('For Inspection', 'For Inspection'), ('Ongoing Inspection', 'Ongoing Inspection'), ('Estimated Bill Created', 'Estimated Bill Created'), ('For Booking', 'For Booking'), ('For Treatment', 'For Treatment'), ('Ongoing Treatment', 'Ongoing Treatment'), ('Pending Payment', 'Pending Payment'), ('Payment Confirmed', 'Payment Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='For Confirmation', max_length=50),
        ),
    ]
