# Generated by Django 6.0.2 on 2026-03-27 13:02

from django.db import migrations, models


def seed_service_form_options(apps, schema_editor):
    ServiceFormOption = apps.get_model('sangapp', 'ServiceFormOption')

    seed_values = [
        ('Inspection', 'Type of Property', 'Residential'),
        ('Inspection', 'Type of Property', 'Commercial'),
        ('Inspection', 'Type of Property', 'Industrial'),
        ('Inspection', 'Type of Property', 'Agricultural'),
        ('Inspection', 'Type of Property', 'Mixed Use'),
        ('Inspection', 'Preferred Service', 'General Pest Control Treatment'),
        ('Inspection', 'Preferred Service', 'Termite Control'),
        ('Inspection', 'Preferred Service', 'Rodent Control'),
        ('Inspection', 'Preferred Service', 'Mosquito Control'),
        ('Inspection', 'Preferred Service', 'Bed Bug Treatment'),
        ('Inspection', 'Preferred Service', 'Cockroach Control'),
        ('Inspection', 'Preferred Service', 'Other'),
        ('Inspection', 'Pest Problems', 'Termites'),
        ('Inspection', 'Pest Problems', 'Rodents'),
        ('Inspection', 'Pest Problems', 'Mosquitoes'),
        ('Inspection', 'Pest Problems', 'Bed Bugs'),
        ('Inspection', 'Pest Problems', 'Cockroaches'),
        ('Inspection', 'Pest Problems', 'Ants'),
        ('Inspection', 'Pest Problems', 'Flies'),
        ('Inspection', 'Pest Problems', 'Spiders'),
        ('Inspection', 'Pest Problems', 'Other'),
        ('Treatment', 'Treatment Service', 'General Pest Control Treatment'),
        ('Treatment', 'Treatment Service', 'Termite Control'),
        ('Treatment', 'Treatment Service', 'Rodent Control'),
        ('Treatment', 'Treatment Service', 'Mosquito Control'),
        ('Treatment', 'Treatment Service', 'Bed Bug Treatment'),
        ('Treatment', 'Treatment Service', 'Cockroach Control'),
        ('Treatment', 'Treatment Service', 'Other'),
        ('Service Report Submission', 'Service Done', 'General Pest Control Treatment'),
        ('Service Report Submission', 'Service Done', 'Termite Control'),
        ('Service Report Submission', 'Service Done', 'Rodent Control'),
        ('Service Report Submission', 'Service Done', 'Mosquito Control'),
        ('Service Report Submission', 'Service Done', 'Bed Bug Treatment'),
        ('Service Report Submission', 'Service Done', 'Cockroach Control'),
        ('Service Report Submission', 'Chemicals Used', 'Baygon'),
        ('Service Report Submission', 'Chemicals Used', 'Muriatic Acid'),
        ('Service Report Submission', 'Chemicals Used', 'Solignum'),
        ('Service Report Submission', 'Levels of Infestation', 'Low'),
        ('Service Report Submission', 'Levels of Infestation', 'Medium'),
        ('Service Report Submission', 'Levels of Infestation', 'High'),
        ('Payment Proof Submission', 'Bank Used for Payment', 'BDO'),
        ('Payment Proof Submission', 'Bank Used for Payment', 'BPI'),
        ('Payment Proof Submission', 'Bank Used for Payment', 'Landbank'),
        ('Payment Proof Submission', 'Bank Used for Payment', 'Metrobank'),
        ('Payment Proof Submission', 'Payment Type', 'Online Bank Transfer'),
        ('Payment Proof Submission', 'Payment Type', 'Over-the-counter Deposit'),
        ('Payment Proof Submission', 'Payment Type', 'E-Wallet Transfer'),
    ]

    for form_section, field_name, option_value in seed_values:
        ServiceFormOption.objects.get_or_create(
            form_section=form_section,
            field_name=field_name,
            option_value=option_value,
            defaults={'is_active': True},
        )


def unseed_service_form_options(apps, schema_editor):
    ServiceFormOption = apps.get_model('sangapp', 'ServiceFormOption')
    ServiceFormOption.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('sangapp', '0017_alter_service_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceFormOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_section', models.CharField(max_length=100)),
                ('field_name', models.CharField(max_length=100)),
                ('option_value', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'service_form_options',
                'ordering': ['form_section', 'field_name', 'option_value'],
                'unique_together': {('form_section', 'field_name', 'option_value')},
            },
        ),
        migrations.RunPython(seed_service_form_options, unseed_service_form_options),
    ]
