# Generated by Django 6.0.2 on 2026-03-27 13:46

import django.db.models.deletion
from django.db import migrations, models


def seed_chemicals_and_backfill(apps, schema_editor):
    Chemical = apps.get_model('sangapp', 'Chemical')
    ServiceReportChemical = apps.get_model('sangapp', 'ServiceReportChemical')
    InvoiceItemOption = apps.get_model('sangapp', 'InvoiceItemOption')
    InvoiceItem = apps.get_model('sangapp', 'InvoiceItem')
    ServiceFormOption = apps.get_model('sangapp', 'ServiceFormOption')

    predefined_chemicals = [
        (1, 'Temprid', 'mL'),
        (2, 'Maxforce', 'g'),
        (3, 'Racumin', 'g'),
        (4, 'Baygon', 'mL'),
        (5, 'Muriatic Acid', 'mL'),
        (6, 'Solignum', 'mL'),
    ]

    for chemical_id, name, unit in predefined_chemicals:
        Chemical.objects.update_or_create(
            id=chemical_id,
            defaults={
                'name': name,
                'standard_unit_measure': unit,
                'is_active': True,
            },
        )

    treatment_options = [
        'Bed Bug Treatment',
        'Cockroach Control',
        'General Pest Control Treatment',
        'Mosquito Control',
        'Rodent Control',
        'Termite Control',
    ]
    for option_value in treatment_options:
        ServiceFormOption.objects.get_or_create(
            form_section='Treatment',
            field_name='Treatment Service',
            option_value=option_value,
            defaults={'is_active': True},
        )

    chemicals_by_name = {
        chemical.name.lower(): chemical.id
        for chemical in Chemical.objects.all()
    }

    for usage in ServiceReportChemical.objects.all():
        if usage.chemical_id:
            continue
        lookup = (usage.chemical_name or '').strip().lower()
        matched_id = chemicals_by_name.get(lookup)
        if matched_id:
            usage.chemical_id = matched_id
            if not usage.unit_measure:
                usage.unit_measure = Chemical.objects.get(id=matched_id).standard_unit_measure
            usage.save(update_fields=['chemical_id', 'unit_measure'])

    option_map = {
        option.name.lower(): option.id
        for option in InvoiceItemOption.objects.all()
    }

    for item in InvoiceItem.objects.all():
        if item.service_item_id:
            continue
        matched_option_id = option_map.get((item.item_type or '').strip().lower())
        if matched_option_id:
            item.service_item_id = matched_option_id
            item.save(update_fields=['service_item'])


def unseed_chemicals(apps, schema_editor):
    Chemical = apps.get_model('sangapp', 'Chemical')
    Chemical.objects.filter(id__in=[1, 2, 3, 4, 5, 6]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('sangapp', '0018_serviceformoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chemical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('standard_unit_measure', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'chemicals',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='service_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_lines', to='sangapp.invoiceitemoption'),
        ),
        migrations.AddField(
            model_name='invoiceitemoption',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='servicereportchemical',
            name='chemical_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='servicereportchemical',
            name='unit_measure',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='servicereportchemical',
            name='chemical',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usages', to='sangapp.chemical'),
        ),
        migrations.RunPython(seed_chemicals_and_backfill, unseed_chemicals),
    ]
