# Generated by Django 6.0.2 on 2026-04-02 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sangapp', '0023_serviceformoption_scoped_option_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesRepresentative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Sales', max_length=100)),
                ('last_name', models.CharField(default='Representative', max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sales_representatives',
            },
        ),
        migrations.RemoveField(
            model_name='property',
            name='country',
        ),
        migrations.AddField(
            model_name='serviceformoption',
            name='account_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='serviceformoption',
            name='additional_information',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='serviceformoption',
            name='application_method',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='serviceformoption',
            name='dilution_rate',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='serviceformoption',
            name='problem_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='serviceformoption',
            name='recommendation_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='serviceformoption',
            name='target_pest',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='PaymentProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(max_length=100)),
                ('bank_used', models.CharField(max_length=255)),
                ('account_number', models.CharField(blank=True, max_length=100)),
                ('reference_number', models.CharField(max_length=255)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('proof_file', models.FileField(upload_to='payment_proofs/')),
                ('status', models.CharField(choices=[('For Validation', 'For Validation'), ('Validated', 'Validated'), ('Rejected', 'Rejected')], default='For Validation', max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_proofs', to='sangapp.customer')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_proofs', to='sangapp.invoice')),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_proof', to='sangapp.service')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_payment_proofs', to='sangapp.salesrepresentative')),
            ],
            options={
                'db_table': 'payment_proofs',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='RemittanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remittance_records', to='sangapp.invoice')),
                ('payment_proof', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='remittance_record', to='sangapp.paymentproof')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remittance_records', to='sangapp.service')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remittance_records', to='sangapp.salesrepresentative')),
            ],
            options={
                'db_table': 'remittance_records',
                'ordering': ['-created_at'],
            },
        ),
    ]
