# Generated by Django 6.0.2 on 2026-04-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sangapp', '0026_servicereportarea_date'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('service',), name='unique_invoice_per_service'),
        ),
    ]
