# Generated by Django 6.0.2 on 2026-04-22 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sangapp", "0028_customer_is_active_salesrepresentative_is_active_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowNotificationLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_key", models.CharField(max_length=255, unique=True)),
                ("event_type", models.CharField(max_length=100)),
                ("recipient_role", models.CharField(max_length=50)),
                ("recipient_email", models.EmailField(max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("sent", "Sent"), ("failed", "Failed")],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("triggered_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workflow_notification_logs",
                        to="sangapp.service",
                    ),
                ),
            ],
            options={
                "db_table": "workflow_notification_logs",
                "ordering": ["-triggered_at"],
            },
        ),
    ]
